[pytest]
addopts = -v --alluredir=allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning

markers =
    smoke: Быстрая проверка основных функций
    regression: Полная проверка регресса
    order: Тесты заказа самоката
    faq: Тесты вопросов и ответов
    navigation: Тесты навигации
    